{% set version = "0.12.0" %}

package:
  name: fairlearn
  version: {{ version }}

source:
  url: https://github.com/fairlearn/fairlearn/archive/v{{ version }}.tar.gz
  sha256: cd967f111ee801b7f6c98b2ac557574a4c43bbe989e25cc67f2bd35e699fd553

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >=1.24.4
    - pandas >=2.0.3
    - scikit-learn >=1.2.1
    - scipy >=1.9.3

test:
  imports:
    - fairlearn

about:
  home: https://github.com/fairlearn/fairlearn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and easy fairness assessment and unfairness mitigation

  description: |
    The fairlearn project seeks to enable anyone involved in the development of
    artificial intelligence (AI) systems to assess their system's fairness and
    mitigate the observed unfairness.
  doc_url: https://fairlearn.readthedocs.io/
  dev_url: https://github.com/fairlearn/fairlearn

extra:
  recipe-maintainers:
    - romanlutz
    - riedgar-ms
    - adrinjalali
    - TamaraAtanasoska
